#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <logic_analyzer_icons.h>

int32_t logic_analyzer_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm logic_analyzer!");

    return 0;
}
