#include <furi.h>
#include "logic_analyzer.h"
#include "scenes/la_scene.h"
#include "util/la_utils.h"
/* generated by fbt from .png files in images folder */
#include <logic_analyzer_icons.h>

// view dispatcher event callbacks to scene manager event
bool la_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "la_scene_manager_custom_event_callback");
    furi_assert(context);
    LAApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}
bool la_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "la_scene_manager_navigation_event_callback");
    furi_assert(context);
    LAApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

void logic_analyzer_free(LAApp* app) {
    FURI_LOG_T(TAG, "free logic analyzer");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, LA_GpioList);
    view_dispatcher_remove_view(app->view_dispatcher, LA_SelectPort);
    view_dispatcher_remove_view(app->view_dispatcher, LA_Dialog);
    view_dispatcher_free(app->view_dispatcher);
    // free scenes
    submenu_free(app->gpio_list);
    variable_item_list_free(app->select_port);
    dialog_ex_free(app->dialog);

    la_gpio_items_free(app->gpio_items);

    free(app->cfg->port_connections);
    free(app->cfg);
    free(app);
}

void logic_analyzer_scene_manager_init(LAApp* app) {
    FURI_LOG_T(TAG, "logic_analyzer_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&la_scene_handlers, app);
}

void logic_analyzer_view_dispatcher_init(LAApp* app) {
    // alocate view dispatcher
    FURI_LOG_T(TAG, "logic_analyzer_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();

    // allocate views
    app->gpio_list = submenu_alloc();
    app->select_port = variable_item_list_alloc();
    app->dialog = dialog_ex_alloc();

    // assign event context
    FURI_LOG_D(TAG, "setting callbacks");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    // assign event callbacks
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, la_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, la_scene_manager_navigation_event_callback);

    // add views to the dispatcher, indexed by their enum value
    FURI_LOG_D(TAG, "adding views");
    view_dispatcher_add_view(app->view_dispatcher, LA_GpioList, submenu_get_view(app->gpio_list));
    view_dispatcher_add_view(
        app->view_dispatcher, LA_SelectPort, variable_item_list_get_view(app->select_port));
    view_dispatcher_add_view(app->view_dispatcher, LA_Dialog, dialog_ex_get_view(app->dialog));
}

LAApp* logic_analyzer_init() {
    FURI_LOG_T(TAG, "init");
    LAApp* app = malloc(sizeof(LAApp));
    app->cfg = malloc(sizeof(LAConfig));
    app->cfg->port_connections = malloc(sizeof(LAPortConnection));

    logic_analyzer_scene_manager_init(app);
    logic_analyzer_view_dispatcher_init(app);

    return app;
}

int32_t logic_analyzer_app(void* p) {
    UNUSED(p);
    LAApp* app = logic_analyzer_init();

    // alloc gpio items
    app->gpio_items = la_gpio_items_alloc();

    // set the scene and launch the main loop
    app->gui = furi_record_open(RECORD_GUI);

    view_dispatcher_attach_to_gui(app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);
    // FIXME: CRASH - NULL pointer dereference
    scene_manager_next_scene(app->scene_manager, LaSceneGpioList);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "Finishing...");
    furi_record_close(RECORD_GUI);
    logic_analyzer_free(app);
    return 0;
}
