#include <furi.h>
#include "logic_analyzer.h"
/* generated by fbt from .png files in images folder */
#include <logic_analyzer_icons.h>
#define TAG "logic_analyzer"

int32_t logic_analyzer_app(void* p) {
    UNUSED(p);
    LAApp* app = logic_analyzer_init();

    // set the scene and launch the main loop
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    // FIXME: CRASH - NULL pointer dereference
    scene_manager_next_scene(app->scene_manager, LA_Menu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "Finishing...");
    furi_record_close(RECORD_GUI);
    logic_analyzer_free(app);
    return 0;
}

LAApp* logic_analyzer_init() {
    FURI_LOG_T(TAG, "init");
    LAApp* app = malloc(sizeof(LAApp));

    logic_analyzer_scene_manager_init(app);
    logic_analyzer_view_dispatcher_init(app);

    return app;
}

void logic_analyzer_scene_manager_init(LAApp* app) {
    FURI_LOG_T(TAG, "init scene manager & scene event handlers");
    app->scene_manager = scene_manager_alloc(&la_scene_event_handler, app);
}

void logic_analyzer_view_dispatcher_init(LAApp* app) {
    // alocate view dispatcher
    FURI_LOG_T(TAG, "init vew dispatcher & views");
    app->view_dispatcher = view_dispatcher_alloc();

    // allocate vies
    app->menu = submenu_alloc();

    // assign event context
    FURI_LOG_D(TAG, "setting callbacks");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    // assign event callbacks
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, la_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, la_scene_manager_navigation_event_callback);

    // add views to the dispatcher, indexed by their enum value
    FURI_LOG_D(TAG, "adding view submenu");
    view_dispatcher_add_view(app->view_dispatcher, LA_Menu, submenu_get_view(app->menu));
}

// view dispatcher event callbacks to scene manager event
bool la_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "redirecting view dispatcher custom event callback to scene manager");
    furi_assert(context);
    LAApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}
bool la_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "redirecting view dispatcher navigation event callback to scene manager");
    furi_assert(context);
    LAApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

void logic_analyzer_free(LAApp* app) {
    FURI_LOG_T(TAG, "free logic analyzer");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, LA_Menu);
    view_dispatcher_free(app->view_dispatcher);
    submenu_free(app->menu);
    free(app);
}

void la_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "enter main menu");
    LAApp* app = context;
    submenu_reset(app->menu);

    // add menu entries
    for(int i = 0; i < 10; i++) {
        // Generate label
        char* str = (char*)malloc(20 * sizeof(char));
        str[0] = '\0';
        char num_str[10];
        la_int_to_str(i, num_str);
        la_concat(str, num_str);
        la_concat(str, ". Element");

        submenu_add_item(app->menu, str, i, la_menu_callback_main_menu, app);
    }

    view_dispatcher_switch_to_view(app->view_dispatcher, LA_Menu);
}

void la_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "callback main menu");
    LAApp* app = context;
    scene_manager_handle_custom_event(app->scene_manager, index);
}

bool la_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "handle event in main menu");
    LAApp* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom: // is a custom event
        switch(event.event) { // handle custom event, event.event is the id in the menu
        default:
            scene_manager_next_scene(app->scene_manager, LA_Menu);
            consumed = true;
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void la_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "exit main menu");
    LAApp* app = context;
    submenu_reset(app->menu);
}

// <-------- Utility Functions -------->
void la_int_to_str(int num, char* str) {
    int i = 0;
    if(num == 0) {
        str[i++] = '0';
    } else {
        while(num > 0) {
            str[i++] = (num % 10) + '0';
            num /= 10;
        }
    }
    str[i] = '\0';
    for(int j = 0; j < i / 2; j++) {
        char temp = str[j];
        str[j] = str[i - j - 1];
        str[i - j - 1] = temp;
    }
}

void la_concat(char* dest, const char* src) {
    while(*dest) {
        dest++;
    }
    while(*src) {
        *dest = *src;
        dest++;
        src++;
    }
    *dest = '\0';
}
